### ISSUE TITLE
Audio buttons not working

### ISSUE THREAD

**Issue by phamthanhnam** [hansyao/Hackintosh_Monterey_M4800#10]
The three buttons for audio (mute, volume down, volume up) at the top left didn't work.

However they work out of the box with VoodooPS2Controller kext (and plugins) from acidanthera team (version 2.2.8), despite of lack of fix for some function keys (Fn+F3, Fn+F5, Fn+F8, SysRq, PrntScrn, Pause, Calc, navigation mode on keypads). The brightness keys (Fn+Up, Fn+Down) work also if I use their kext with your SSDT patch. Their kext has also Magic Trackpad 2 emulation for multitouch gestures on touchpad.

Should it be better if you rebase your work for fixing other hot keys? DrHurt's VoodooPS2Controller has not been updated for a long time.

**Comment by hansyao** [comment]
> The three buttons for audio (mute, volume down, volume up) at the top left didn't work.
> 
> However they work out of the box with VoodooPS2Controller kext (and plugins) from acidanthera team (version 2.2.8), despite of lack of fix for some function keys (Fn+F3, Fn+F5, Fn+F8, SysRq, PrntScrn, Pause, Calc, navigation mode on keypads). The brightness keys (Fn+Up, Fn+Down) work also if I use their kext with your SSDT patch. Their kext has also Magic Trackpad 2 emulation for multitouch gestures on touchpad.
> 
> Should it be better if you rebase your work for fixing other hot keys? DrHurt's VoodooPS2Controller has not been updated for a long time.

I believe your hardware is not fully same as mine. Or you did not use my completed EFI package.
Keyboard/trackpad are perfect with my customized VoodooPS2Controller and all hotkeys are filled.
and for audio it's fully compatible with the [AppleALC](https://github.com/acidanthera/AppleALC/pull/773) as I submitted the pull request and merged to acidanthera repo in March 2022.

If you look into the feedbacks from other folks, there's no one have such kind of issues you described above since my first commit.

**Comment by phamthanhnam** [comment]
Thanks for your reply.

Yes, my laptop is not exactly the same as yours. I have Intel 7260 wifi card, Nvidia K2100M GPU instead. Running dmidecode -t baseboard in Linux without OpenCore give Product Name: 0X3C7N. I had to edit my config.plist and some kexts, otherwise my machine won't boot with your EFI package. But your SSDT is OK. I didn't have to change anything in ACPI section. The brightness keys and 3 audio buttons work out of the box with acidanthera's VoodooPS2Controller kext. If I use your VoodooPS2Controller kext, other hot keys (trackpad toggle, Calc, keypads...) are recognized and fixed, but audio buttons break, and it seems bizarre.

I can confirm that AppleALC works with layout-id 59.

I think there are not many hackintoshers with this specific laptop, so there are not enough feedbacks (maybe they didn't find the issue, or maybe they didn't bother with the issue).

Can you test your laptop with VoodooPS2Controller from acidanthera to see if audio buttons work? I think there has been quite a lof of improvement (security, features or performance) in acidanthera's ALPS driver since DrHurt's last commit (5 years ago), because acidantherea team are actively developing OpenCore. Rebasing your fixes on acidanthera's work can give you benefit, and merging your work into their repository can save you from upkeep and maintenance with future versions of macOS.

**Comment by hansyao** [comment]
> Thanks for your reply.
> 
> Yes, my laptop is not exactly the same as yours. I have Intel 7260 wifi card, Nvidia K2100M GPU instead. Running dmidecode -t baseboard in Linux without OpenCore give Product Name: 0X3C7N. I had to edit my config.plist and some kexts, otherwise my machine won't boot with your EFI package. But your SSDT is OK. I didn't have to change anything in ACPI section. The brightness keys and 3 audio buttons work out of the box with acidanthera's VoodooPS2Controller kext. If I use your VoodooPS2Controller kext, other hot keys (trackpad toggle, Calc, keypads...) are recognized and fixed, but audio buttons break, and it seems bizarre.
> 
> I can confirm that AppleALC works with layout-id 59.
> 
> I think there are not many hackintoshers with this specific laptop, so there are not enough feedbacks (maybe they didn't find the issue, or maybe they didn't bother with the issue).
> 
> Can you test your laptop with VoodooPS2Controller from acidanthera to see if audio buttons work? I think there has been quite a lof of improvement (security, features or performance) in acidanthera's ALPS driver since DrHurt's last commit (5 years ago), because acidantherea team are actively developing OpenCore. Rebasing your fixes on acidanthera's work can give you benefit, and merging your work into their repository can save you from upkeep and maintenance with future versions of macOS.

No.  The trackpad of M4800 not work in acidanthera's VoodooPS2Controller. Everything works perfect with my own M4800 with my current customized ALPS driver. There's nothing new for the ALPS driver. Acidanthera's VoodooPS2Controller is just combined everything together to make more machine models compatible.  Trust me that it's not stable enough rather than my customized driver which removed all unnecessary codes but only kept ALPS for Dell M4800.

**Comment by phamthanhnam** [comment]
Using your kext, my volume buttons are in fact recognized as keys but on-screen display is not shown. I suppose that they are not mapped to standard volume keys. I also find that the shortcuts Cmd+Q/W/A/S/O/Z/X/C/V... don't work. The hardware is likely same same but different. So instead of trying to correct these things with your kext, I've made my own VoodooPS2Controller.kext based on acidanthera's VoodooPS2 with your guide: https://github.com/hansyao/OS-X-ALPS-DRIVER/blob/master/M4800_keyboard_fix.md.

Luckily, there's not much change in code structure, so I can apply the keyboard fix successfully. I am now happy with my own kext.
