### ISSUE TITLE
NVIDIA Quadro K1100M does not work with geekbench OpenCL benchmark nor iPhone Simulator (black screen)

### ISSUE THREAD

**Issue by avelarfe** [hansyao/Hackintosh_Monterey_M4800#2]
Is there any additional kext that I need to add, despite the ones that the nvidia patcher adds?
Is it possible to just use the nvidia and disable the intel for better performance?

Running this issue on 12.0.1

**Comment by hansyao** [comment]
> Is there any additional kext that I need to add, despite the ones that the nvidia patcher adds? Is it possible to just use the nvidia and disable the intel for better performance?
> 
> Running this issue on 12.0.1

Did you inject your own edid?

**Comment by avelarfe** [comment]
I did not. Just installed https://github.com/chris1111/Geforce-Kepler-patcher

**Comment by hansyao** [comment]
* Inject your own [edid](https://github.com/hansyao/Hackintosh_Monterey_M4800/blob/dbe637f9f9f20656d42153379cd94792199af3a6/SSDT-Dell-M4800.dsl#L938-L948) and try again (by replace edid in dsl and recompile). 

* in boot-args: -wegswitchgpu to disable internal GPU when external GPU is installed (or add switch-to-external-gpu property to IGPU)

**Comment by avelarfe** [comment]
How do i inject? is there any guide?

**Comment by avelarfe** [comment]
after upgraded to 12.3 it says "no kext loaded" for eGPU:
![Screen Shot 2022-03-31 at 13 56 45](https://user-images.githubusercontent.com/21061728/161109555-ade6f07a-f519-450a-8cdd-d31f0e9832e4.png)

**Comment by avelarfe** [comment]
I've installed the patch again, now it's showing as it was before, but still doesn't work with rendering OpenCL and Simulator on the eGPU.

**Comment by hansyao** [comment]
> How do i inject? is there any guide?

https://github.com/hansyao/Hackintosh_M4800/issues/4#issuecomment-917599933

**Comment by avelarfe** [comment]
I dont have windows to do that :/

**Comment by hansyao** [comment]
> I dont have windows to do that :/

You have to get edid in windows or linux. Hackintosh can not generate correct edid.

**Comment by hansyao** [comment]
One question. Did you connect the external monitor to test?

**Comment by avelarfe** [comment]
> One question. Did you connect the external monitor to test?

I did not, does it have to be on display port in the right or can use the hdmi on the back?

**Comment by hansyao** [comment]
> > One question. Did you connect the external monitor to test?
> 
> I did not, does it have to be on display port in the right or can use the hdmi on the back?

Both would be ok however display port would be much better.

**Comment by avelarfe** [comment]
Download ➤ [Geforce-Kepler-patcher-V2](https://github.com/chris1111/Geforce-Kepler-patcher/releases/tag/V2)[](https://github.com/chris1111/Geforce-Kepler-patcher#download--geforce-kepler-patcher-v1)
Download ➤ [Geforce-Kepler-patcher-V1](https://github.com/chris1111/Geforce-Kepler-patcher/releases/tag/V1)


I have installed v2, do I need to install only v1?

**Comment by hansyao** [comment]
Only v2 would be okay.

**Comment by avelarfe** [comment]
Is it possible do disable iGPU in bios and still install?

**Comment by avelarfe** [comment]
> Is it possible do disable iGPU in bios and still install?

The answer is no.

Is it possible to run a 4k monitor with this laptop? I can using windows, I was wondering if it will work in this one using the dock as well.

**Comment by hansyao** [comment]
> > Is it possible do disable iGPU in bios and still install?
> 
> The answer is no.
> 
> Is it possible to run a 4k monitor with this laptop? I can using windows, I was wondering if it will work in this one using the dock as well.

* if you wanna disable iGPU in bois, you may change GFX0 to iGPU in dsl and recompile. it's possible and would work though I would not do this.
* for 4K external monitor, it certainly works as I tested very well in my Laptap both for HDMI and DP port.

**Comment by avelarfe** [comment]
And how I recompile? Is it possible to do in macOS or I need to use Windows?

**Comment by avelarfe** [comment]
IN MACIASL I get these when I try to compile, even tho I din't change anything:
![Captura de Tela 2022-05-21 às 19 06 07](https://user-images.githubusercontent.com/21061728/169670433-30e85232-594a-46bb-821f-f501dc0be0de.png)

**Comment by avelarfe** [comment]
Ok, I've opened de dsl correctly, but what exactly I need to change init?

**Comment by avelarfe** [comment]
This is my ssdt:
`Name (GFX0._STA, Zero)  // _STA: Status
            Device (IGPU)
            {
                Name (_ADR, 0x00020000)  // _ADR: Address
                Method (_INI, 0, NotSerialized)  // _INI: Initialize
                {
                    \_SB.PCI0.GFX0._ADR = Zero
                }

                Method (_DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
                {
                    If ((Arg2 == Zero))
                    {
                        Return (Buffer (One)
                        {
                             0x03                                             // .
                        })
                    }

                    Local0 = Package (0x1A)
                        {
                            "device-id", 
                            Buffer (0x04)
                            {
                                 0x12, 0x04, 0x00, 0x00                           // ....
                            }, 

                            "@0,backlight-control", 
                            Buffer (0x04)
                            {
                                 0x01, 0x00, 0x00, 0x00                           // ....
                            }, 

                            "AAPL,backlight-control", 
                            Buffer (0x04)
                            {
                                 0x01, 0x00, 0x00, 0x00                           // ....
                            }, 

                            "AAPL00,backlight-control", 
                            Buffer (0x04)
                            {
                                 0x01, 0x00, 0x00, 0x00                           // ....
                            }, 

                            "applbkl", 
                            Buffer (0x04)
                            {
                                 0x01, 0x00, 0x00, 0x00                           // ....
                            }, 

                            "pci-aspm-default", 
                            0x03, 
                            "AAPL,ig-platform-id", 
                            Buffer (0x04)
                            {
                                 0x06, 0x00, 0x26, 0x0A                           // ..&.
                            }, 

                            "framebuffer-patch-enable", 
                            Buffer (0x04)
                            {
                                 0x01, 0x00, 0x00, 0x00                           // ....
                            }, 

                            "framebuffer-cursormem", 
                            Buffer (0x04)
                            {
                                 0x00, 0x00, 0x90, 0x00                           // ....
                            }, 

                            "framebuffer-unifiedmem", 
                            Buffer (0x04)
                            {
                                 0x00, 0x00, 0x00, 0x80                           // ....
                            }, 

                            "framebuffer-fbmem", 
                            Buffer (0x04)
                            {
                                 0x00, 0x00, 0x90, 0x00                           // ....
                            }, 

                            "hda-gfx", 
                            Buffer (0x0A)
                            {
                                "onboard-1"
                            }, 

                            "AAPL00,override-no-connect", 
                            Buffer (0x80)
                            {
                                /* 0000 */  0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00,  // ........
                                /* 0008 */  0x30, 0xE4, 0x6F, 0x04, 0x00, 0x00, 0x00, 0x00,  // 0.o.....
                                /* 0010 */  0x00, 0x18, 0x01, 0x04, 0x95, 0x22, 0x13, 0x78,  // .....".x
                                /* 0018 */  0xEA, 0xDC, 0x95, 0xA3, 0x58, 0x55, 0xA0, 0x26,  // ....XU.&
                                /* 0020 */  0x0D, 0x50, 0x54, 0x00, 0x00, 0x00, 0x01, 0x01,  // .PT.....
                                /* 0028 */  0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,  // ........
                                /* 0030 */  0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x2E, 0x36,  // .......6
                                /* 0038 */  0x80, 0xA0, 0x70, 0x38, 0x1F, 0x40, 0x30, 0x64,  // ..p8.@0d
                                /* 0040 */  0x35, 0x00, 0x58, 0xC2, 0x10, 0x00, 0x00, 0x1A,  // 5.X.....
                                /* 0048 */  0x52, 0x2B, 0x80, 0xA0, 0x70, 0x38, 0x1F, 0x40,  // R+..p8.@
                                /* 0050 */  0x30, 0x20, 0x35, 0x00, 0x58, 0xC2, 0x10, 0x00,  // 0 5.X...
                                /* 0058 */  0x00, 0x1A, 0x00, 0x00, 0x00, 0xFE, 0x00, 0x33,  // .......3
                                /* 0060 */  0x38, 0x37, 0x34, 0x59, 0x80, 0x31, 0x35, 0x36,  // 874Y.156
                                /* 0068 */  0x57, 0x46, 0x36, 0x0A, 0x00, 0x00, 0x00, 0x00,  // WF6.....
                                /* 0070 */  0x00, 0x00, 0x41, 0x31, 0x9E, 0x00, 0x10, 0x00,  // ..A1....
                                /* 0078 */  0x00, 0x0A, 0x01, 0x0A, 0x20, 0x20, 0x00, 0x4E   // ....  .N
                            }
                        }
                    DTGP (Arg0, Arg1, Arg2, Arg3, RefOf (Local0))
                    Return (Local0)
                }

                Device (PNLF)
                {
                    Name (_HID, EisaId ("APP0002"))  // _HID: Hardware ID
                    Name (_CID, "backlight")  // _CID: Compatible ID
                    Name (_UID, 0x13)  // _UID: Unique ID
                    Name (_STA, 0x0B)  // _STA: Status
                }

                Method (BRT6, 2, NotSerialized)
                {
                    If ((Arg0 == One))
                    {
                        Notify (\_SB.PCI0.LPCB.PS2K, 0x0406)
                        Notify (\_SB.PCI0.GFX0.LCD, 0x86) // Device-Specific
                    }

                    If ((Arg0 & 0x02))
                    {
                        Notify (\_SB.PCI0.LPCB.PS2K, 0x0405)
                        Notify (\_SB.PCI0.GFX0.LCD, 0x87) // Device-Specific
                    }
                }
            }`

And this is my quadro device path:
`PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)`

Do I just change the paths?
