### ISSUE TITLE
EFI USB installer 

### ISSUE THREAD

**Issue by AFadlian06** [hansyao/Hackintosh_Monterey_M4800#4]
Hi, friend..i'm try to install monterey on my m4800. I create usb install monterey, i use EFI you shared..then I boot my usb but wont booting os monterey...and automatically reboot again. What wrong?
Can you shared efi folder on usb installer too?

**Comment by hansyao** [comment]
did you point to [OpenCore.efi](https://github.com/hansyao/Hackintosh_Monterey_M4800/blob/master/EFI/OC/OpenCore.efi) in your EFI BIOS settings?

**Comment by AFadlian06** [comment]
Yes, i copied that efi folder to usb installer. but monterey not booting then my notebook restart again..

**Comment by hansyao** [comment]
> Yes, i copied that efi folder to usb installer. but monterey not booting then my notebook restart again..

No. you didn't understand what I was saying. You need to point to `EFI/OC/OpenCore.efi` in BIOS EFI Settings prior to reboot your laptop.

**Comment by AFadlian06** [comment]
> > Yes, i copied that efi folder to usb installer. but monterey not booting then my notebook restart again..
> 
> No. you didn't understand what I was saying. You need to point to `EFI/OC/OpenCore.efi` in BIOS EFI Settings prior to reboot your laptop.

![IMG_20220405_141253](https://user-images.githubusercontent.com/97341367/161699114-a4c74aba-636b-4c50-8063-e1335de67aa0.jpg)
Please, see my picture..

**Comment by AFadlian06** [comment]
> > > Yes, i copied that efi folder to usb installer. but monterey not booting then my notebook restart again..
> > 
> > 
> > No. you didn't understand what I was saying. You need to point to `EFI/OC/OpenCore.efi` in BIOS EFI Settings prior to reboot your laptop.
> 
> ![IMG_20220405_141253](https://user-images.githubusercontent.com/97341367/161699114-a4c74aba-636b-4c50-8063-e1335de67aa0.jpg) Please, see my picture..
 I booted my usb installer monterey. After that my notebook is reboot wont boot into monterey install..

**Comment by AFadlian06** [comment]
Please my video..

**Comment by AFadlian06** [comment]
Please see my video..
https://youtu.be/UxylWChgCZs

**Comment by hansyao** [comment]
> Please see my video.. https://youtu.be/UxylWChgCZs

please check your mainboard and hardware list whether it's same as [mine](https://github.com/hansyao/Hackintosh_Monterey_M4800/blob/master/SSDT-Dell-M4800.dsl#L14-L53) prior to apply my EFI.

**Comment by AFadlian06** [comment]
I used same as you, previous i used efi bigsur..but ok not problem..but this Monterey stuck.

**Comment by AFadlian06** [comment]
You used same efi folder for your usb installer right?

**Comment by hansyao** [comment]
Big sure and Monterey are different EFI.
it's better to clean NVRAM before upgrade to Monterey from Big sur. And replace all EFI files for Monterey.  (NOTE: **DO NOT** keep any old driver injection kexts from Big Sur EFI folders after upgrade to Monterey).

There's no issue to use same EFI for usb installer. either way you can directly upgrade Monterey from Big Sur, only thing you can do is to replace EFI folder prior to the 1st reboot during installation .

if any boot problem, you can follow the generic [guide](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/opencore-issues.html#stuck-on-a-black-screen-before-picker) prior to raising issues.

**Comment by draskostar** [comment]
Hello,

I have same issues as @AFadlian06. 

1. I made bootable usb for Monterey
2. I mounted EFI with OC configurator and put in your EFI folder
3. I then restart and boot my PC from USB but after I choose Install Monterey my pc restarts it self and that's it, installation cannot go further at this point

Thank for keeping our pcs still usable these days. Sorry for my English.

Thanks

**Comment by manhtuanzo** [comment]
I have the same issues My GPU is K2100m can I use your refi for Bigsur and Monterey

**Comment by AFadlian06** [comment]
I'm success install monterey 12.3.1 on my dell m4800. Working perfectly

**Comment by manhtuanzo** [comment]
> I'm success install monterey 12.3.1 on my dell m4800. Working perfectly

Hibro can you share me!

**Comment by AFadlian06** [comment]
![IMG_20220524_170928](https://user-images.githubusercontent.com/97341367/170046491-b69c7b45-0911-47ad-b319-29473dd7ee4c.jpg)

**Comment by manhtuanzo** [comment]
> ![IMG_20220524_170928](https://user-images.githubusercontent.com/97341367/170046491-b69c7b45-0911-47ad-b319-29473dd7ee4c.jpg)

Do you have telegram?
