### ISSUE TITLE
Reboot after a few seconds - how to fix ?

### ISSUE THREAD

**Issue by ds2k5** [hansyao/Hackintosh_Monterey_M4800#5]
Hi,
use your files....
build the SSDT-Dell-M4800 an but it into OC directory.

When select the USB-Key as boot device
i can select the MacOS installer.... ( Monterey 12.3.1 )
 
see the Apple Logo for a few seconds then the M4800 reboot.

How can  I fix this ?

My Hardware is a little bit diffrent to yours:

01:00.0 VGA compatible controller: NVIDIA Corporation GK106GLM [Quadro K2100M] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GK106 HDMI Audio Controller (rev a1)
03:00.0 Network controller: Intel Corporation Wireless 7260 (rev 73)

**Comment by hansyao** [comment]
> Hi, use your files.... build the SSDT-Dell-M4800 an but it into OC directory.
> 
> When select the USB-Key as boot device i can select the MacOS installer.... ( Monterey 12.3.1 )
> 
> see the Apple Logo for a few seconds then the M4800 reboot.
> 
> How can I fix this ?
> 
> My Hardware is a little bit diffrent to yours:
> 
> 01:00.0 VGA compatible controller: NVIDIA Corporation GK106GLM [Quadro K2100M] (rev a1) 01:00.1 Audio device: NVIDIA Corporation GK106 HDMI Audio Controller (rev a1) 03:00.0 Network controller: Intel Corporation Wireless 7260 (rev 73)

you can follow https://github.com/hansyao/Hackintosh_Monterey_M4800/issues/1#issuecomment-1084012890 to solve the issue for intel WIFI driver.

**Comment by ds2k5** [comment]
Hi,
thanks for your info

removed files in   EFI/OC/Kexts

```
AirportBrcmFixup.kext
BlueToolFixup.kext
BrcmFirmwareData.kext
BrcmPatchRAM3.kext

```
an modify the SSDT-Dell-M4800.dsl 

removed this lines:
```

         // bluetooth BCM4352 injection       
        Scope (_SB.PCI0.RP03)
        {
            Scope (PXSX)
            {
                Name (_STA, Zero)
            }

            Device (ARPT)
            {    
                Name (_ADR, Zero)
                Name (_PRW, Package (0x02) {0x09,0x04})
                Name (_SUN, One)
                Method (_DSM, 4, NotSerialized)
                {
                    Store (Package (0x0C) {
                        "AAPL,slot-name", "AirPort",
                        "name", "AirPort Extreme",
                        "model", Buffer () {"Broadcom BCM4352 802.11ac Wireless Network Adapter"},
                        "device_type", Buffer () {"AirPort"},
                        "compatible", "pci14e4,43a0",
                        // "device-id",  Buffer(0x04) { 0xa3, 0x43, 0x00, 0x00 },
                        "built-in", Buffer (One) {0x01}
                    }, Local0)
                    DTGP (Arg0, Arg1, Arg2, Arg3, RefOf (Local0))
                    Return (Local0)
                }

            }
        }

```


rebuild the:  SSDT-Dell-M4800.aml    in EFI/OC/ 



**But the reboot is this there / system did not boot to installer**

**Comment by hansyao** [comment]
> Hi, thanks for your info
> 
> removed files in EFI/OC/Kexts
> 
> ```
> AirportBrcmFixup.kext
> BlueToolFixup.kext
> BrcmFirmwareData.kext
> BrcmPatchRAM3.kext
> ```
> 
> an modify the SSDT-Dell-M4800.dsl
> 
> removed this lines:
> 
> ```
> 
>          // bluetooth BCM4352 injection       
>         Scope (_SB.PCI0.RP03)
>         {
>             Scope (PXSX)
>             {
>                 Name (_STA, Zero)
>             }
> 
>             Device (ARPT)
>             {    
>                 Name (_ADR, Zero)
>                 Name (_PRW, Package (0x02) {0x09,0x04})
>                 Name (_SUN, One)
>                 Method (_DSM, 4, NotSerialized)
>                 {
>                     Store (Package (0x0C) {
>                         "AAPL,slot-name", "AirPort",
>                         "name", "AirPort Extreme",
>                         "model", Buffer () {"Broadcom BCM4352 802.11ac Wireless Network Adapter"},
>                         "device_type", Buffer () {"AirPort"},
>                         "compatible", "pci14e4,43a0",
>                         // "device-id",  Buffer(0x04) { 0xa3, 0x43, 0x00, 0x00 },
>                         "built-in", Buffer (One) {0x01}
>                     }, Local0)
>                     DTGP (Arg0, Arg1, Arg2, Arg3, RefOf (Local0))
>                     Return (Local0)
>                 }
> 
>             }
>         }
> ```
> 
> rebuild the: SSDT-Dell-M4800.aml in EFI/OC/
> 
> **But the reboot is this there / system did not boot to installer**

must be something wrong and you could check log to see the details to fix it. You can also ask @fearlipe to share you his EFI with you as works well for his intel WIFI.

**Comment by ds2k5** [comment]
>must be something wrong and you could check log to see the details to fix it

how to create a log and store it to USB-Key ?

tryed to enable with OpenCore Configurator but did not find a log

**Comment by hansyao** [comment]
duplicated issue which was solved. refer to #4.

**Comment by H3ADROOM** [comment]
Was the solution for this issue ever given? I am trying to install Monterey too. My machine is slightly different, it has a AMD FirePro M5100 and WiFi module is Intel AX210
