### ISSUE TITLE
Add Bios Settings to readme

### ISSUE THREAD

**Issue by avelarfe** [hansyao/Hackintosh_Monterey_M4800#6]
Could you please add bios settings to readme file? Also screenshots would be nice.

Thanks

**Comment by hansyao** [comment]
> Could you please add bios settings to readme file? Also screenshots would be nice.
> 
> Thanks

only `Secure Boot` **MUST** be disabled. just added the commit https://github.com/hansyao/Hackintosh_Monterey_M4800/commit/feadd33b635d2c1276de9507f33a9f6f084801f1# in readme.
